<Project Sdk="Microsoft.NET.Sdk">

  <!-- Embedded Resources -->
  <ItemGroup>
    <EmbeddedResource Include="Resources\PermissionCatalog.xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRM.Modules.Identity.Domain\HRM.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HRM.BuildingBlocks.Infrastructure\HRM.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

</Project>
