<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HRM.Modules.Attendance.Application\HRM.Modules.Attendance.Application.csproj" />
    <ProjectReference Include="..\HRM.Modules.Attendance.Infrastructure\HRM.Modules.Attendance.Infrastructure.csproj" />
    <ProjectReference Include="..\HRM.Modules.Attendance.Domain\HRM.Modules.Attendance.Domain.csproj" />
  </ItemGroup>

</Project>
